- name: Configure once for all!
  hosts: localhost
  connection: local
  roles:
    - packages
    - nodejs
    - neovim
    - ohmyzsh
    - astrovim
    - fzf
    - lazygit
    - configs
    - opencode
    - shell
