- name: Install OS packages
  become: yes
  ansible.builtin.package:
    name:
      - vim
      - git
      - zsh
      - curl
      - wget
      - tmux
      - autojump
      - cargo
      - unzip
      - ripgrep
      - fd-find
      - lsof
    state: present
  tags: [packages]
