- name: Clone fzf repository
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: '{{ ansible_facts.user_dir }}/.fzf'
    depth: 1
  tags: [fzf]

- name: Run fzf install script
  ansible.builtin.command: '{{ ansible_facts.user_dir }}/.fzf/install --all'
  args:
    creates: '{{ ansible_facts.user_dir }}/.fzf/bin/fzf'
  tags: [fzf]
